version: 2

sources:
  - name: jaffle_shop
    description: A replica of the postgres database
    database: raw
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - not_null
              - unique
      - name: orders
        description: One record per order
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: status
            description: "{{ doc('order_status') }}"
            tests:
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stripe
    description: Incoming stripe payment data.
    database: raw
    tables:

      - name: payment
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: payment_method
            tests:
              - accepted_values:
                  values: ['credit_card', 'bank_transfer', 'gift_card', 'coupon']
          - name: status
            tests:
              - accepted_values:
                  values: ['success', 'fail']